### ISSUE TITLE
Would this work in a Laravel 5 project?

### ISSUE THREAD

**Issue by shealan** [Torann/podcastfeed#1]
Not really an issue as such, but just wondering?

**Comment by Torann** [comment]
I haven't tried it. Will give it a once over now

**Comment by shealan** [comment]
That would be great. Would love to use it :)

**Comment by Torann** [comment]
Just updated the package. You should be all set now :-)

It may take it a few minutes for the changes to make it to packagist/composer.

**Comment by shealan** [comment]
Awesome, thank you!
